#include "mainwindow.h"
#include "ui_mainwindow.h"

MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ui->setupUi(this);
}

MainWindow::~MainWindow()
{
    delete ui;
}

void MainWindow::on_PathBtn_clicked()
{
    QFileDialog dialog;
    dialog.setFileMode(QFileDialog::Directory);
    dialog.setOption(QFileDialog::ShowDirsOnly);
    dialog.setViewMode(QFileDialog::Detail);
    int res = dialog.exec();
    QDir directory;

    ui->textBrowser->clear();

    if (res) {
        directory = dialog.selectedFiles()[0];
        QStringList filesList = directory.entryList(QStringList() << "*.avi",QDir::Files);
        QString fileName;
        foreach(fileName, filesList) {

           ui->textBrowser->append(fileName);
           //ui->textBrowser->append(fileName);
           //QString savefilename = fileName+".txt";
           QString t = fileName.split(".").at(0);
           QFile file(directory.absolutePath()+"/"+t+".txt");
               file.open(QIODevice::WriteOnly | QIODevice::Text);
               QTextStream out(&file);
               out << "This file is generated by Qt\n";

               // optional, as QFile destructor will already do it:
               file.close();
        }
        QFile file(directory.absolutePath()+"/result.txt");
            file.open(QIODevice::WriteOnly | QIODevice::Text);
            QTextStream out(&file);
            out << "This file is generated by Qt\n";

            // optional, as QFile destructor will already do it:
            file.close();
    }
}
